### ISSUE TITLE
Could not resolve the dependencies

### ISSUE THREAD

**Issue by synoptase** [jozefizso/puppet-sublime_text_3#1]
I can't seem to get it working with boxen 3.0.2. Here's how i call it in the `Puppetfile`

```
github "sublime_text_3",    "1.0.0", :repo => "jozefizso/puppet-sublime_text_3"
```

Then a

```
$ > bundle exec librarian-puppet update
```

outputs a `Could not resolve the dependencies.`

Any ideas?

**Comment by jozefizso** [comment]
Hi @synoptase,
thank you using this puppet module.

I forget to make a 1.0.0 release of this module. I created a tag for the release so you should be able to fetch it by librarian-puppet now.
Module is tested with Boxen 2.1.0 but I use it with Boxen 3.0.0 without problems.

**Comment by synoptase** [comment]
Hey -

Works like a charm, thanks!
