### ISSUE TITLE
Is there a way to install packages that are only in the wbond package control like the svn package?

### ISSUE THREAD

**Issue by atomless** [jozefizso/puppet-sublime_text_3#4]

**Comment by jozefizso** [comment]
Hi atomless,
I'm not sure what do you mean by installing wbond only package.

You can install Sublime Text packages from Git repository on GitHub or by downloading .sublime-package from the Internet.

**Comment by ksatirli** [comment]
@atomless I think what you want is this:

```
sublime_text_3::package { 'SFTP':
    source => 'https://sublime.wbond.net/files/3-posix/SFTP.sublime-package'
}

sublime_text_3::package { 'Subversion':
    source => 'https://sublime.wbond.net/files/3-posix/SVN.sublime-package'
}
```

I grabbed those Sublime package URLs from https://sublime.wbond.net/packages_2.json by looking for the URL that would give me a package compatible with my Mac.
