### ISSUE TITLE
no description and no file being saved into installed_packages

### ISSUE THREAD

**Issue by atomless** [jozefizso/puppet-sublime_text_3#5]
I've been trying to install quite a few different packages and mostly they seem ot get installed and work but the listing in the List Packages function lacks a description and the usual remove info - also they don't seem to get a file created in the installed_packages folder.

**Comment by jozefizso** [comment]
Hi atomless, this Boxen module installs packages to Sublime Text to the [Packages](http://docs.sublimetext.info/en/latest/basic_concepts.html#the-packages-directory) directory.

It does not install packages into Package Control as that plugin uses its own proprietary way to manage packages.
